//
// Generated by 'sql2dart'
//

import 'package:sqflite/sqflite.dart';
Future<int> insertMessage(Database db, type,text,) async {
return await db.transaction((txn) async {
return await txn.rawInsert("""INSERT INTO message ( type , text ) VALUES ( ? , ? )""", [type, text],);
});}
